export const crossoverData = {
  "Caballero, Ramiro": {
    "CICHEVSKI, Alejandro": [],
    "Caballero, Ramiro": ["Auriblanco", "Verdirrojo", "Urupán", "Defensores"],
    "Cabot, Marcos": [],
    "Cabral, Fernando": [],
    "Cabrera, Francisco": [],
    "Cabrera, Jorge": [],
    "Cadenasso, Alejandro": [],
    "Calfani, Matías": [],
    "Calone, Nicolas": ["Verdirrojo"],
    "Cambón, Ignacio": [],
    "Camejo, Felipe": [],
    "Campaña, Eduardo": [],
    "Canepa, Juan Pablo": [],
    "Cano, Juan": [],
    "Cano, Sebastián": [],
    "Capalbo, Lucas": [],
    "Caputi, Mateo": [],
    "Carbajal, Nicolas": [],
    "Carballo, Matías0": [],
    "Cardoney, Rodrigo": [],
    "Cardozo Grudnicki, Rodrigo": [],
    "Cardozo, Victor": [],
    "Carrabs, Fabricio": [],
    "Carranza, Joaquín": [],
    "Carrerou, Andrés": [],
    "Carrerou, Ignacio": [],
    "Carril, Rodrigo": ["Auriblanco"],
    "Carro, Fabián": [],
    "Caruso, Diego": [],
    "Carvalho, Gabriel": [],
    "Carvidon, Rodrigo": [],
    "Carvidón, Gonzalo": [],
    "Casalas, Diego": [],
    "Casas, Bruno": [],
    "Castagnaro, Sebastián": [],
    "Castell, Carlos": [],
    "Castello, Sergio": [],
    "Castillo, Facundo": [],
    "Castiñeira, Gonzalo": [],
    "Castro, Favio": [],
    "Castro, Ignacio": [],
    "Castro, Joaquin": [],
    "Castro, Martín": [],
    "Castro, Rodrigo": [],
    "Castro, Santiago": [],
    "Castro, Sebastián": [],
    "Catalá, Nicolás": [],
    "Cavalli, Gastón": [],
    "Cawen, Joaquin": [],
    "Cervi, Maximiliano": ["Verdirrojo"],
    "Cervieri, Diego": [],
    "Chamorro, Pablo": [],
    "Charquero, Claudio": [],
    "Chevalier, Eduardo": [],
    "Chimanoski, Alvin": [],
    "Chiriazis, Jorge": [],
    "Chittadini, Sebastián": [],
    "Cieslinkas, Christian": [],
    "Cieslinkas, Nicolás": [],
    "Clérici, Pablo": [],
    "Cocchi, Franco": [],
    "Coelho, Lorenzo": [],
    "Coelho, Rodrigo": [],
    "Coito, Juan Martín": [],
    "Colman, Camilo": ["Auriblanco"],
    "Colmán, Richard": ["Auriblanco"],
    "Colombo, Angelo": [],
    "Comas, Nicolas": [],
    "Compan, Raul": [],
    "Confalonieri, Alejandro": [],
    "Conti, Nicolás": [],
    "Coronado, Juan": [],
    "Correa, Matías": ["Verdirrojo"],
    "Correa, Mauricio": [],
    "Correa, Maximiliano": [],
    "Corsino, Nicolas": [],
    "Cortes, Geronimo": [],
    "Corti, Nicolás": [],
    "Cortiza, Germán": [],
    "Coselino, Santiago": [],
    "Couto, Agustín": [],
    "Couto, Juan": [],
    "Craig, Brian": [],
    "Crespi, Francisco": [],
    "Cresseri, Andres": [],
    "Crócano, Javier": ["Verdirrojo"],
    "Cuna, Gastón": [],
    "Cuneo, Conrado": [],
    "Curadossi, Bruno": [],
    "Curbelo, Facundo": [],
    "Curbelo, Federico": ["Auriblanco"],
    "Curbelo, Guillermo": [],
    "Cáceres, Hernando": [],
    "Cámpora, Federico": [],
    "Da Costa, Agustin": [],
    "Da Nobrega (Magrao), Carlos": [],
    "Da Rosa, Santiago": [],
    "Da Silva, Hakeem": [],
    "Damico, Gabriel": [],
    "Danglada, Esteban": ["Auriblanco", "Verdirrojo"],
    "De Armas, Rodrigo": [],
    "De Avila, Ronald": [],
    "De Fino, Maximiliano": [],
    "De Gouveia, Matías": ["Verdirrojo"],
    "De Leon, Ignacio": [],
    "De León, Luis": ["Verdirrojo"],
    "De León, Rogelio": ["Verdirrojo"],
    "De Los Santos, Brian": [],
    "De Los Santos, Gaston": [],
    "De Melo, Juan": [],
    "De Pena, Jorge": [],
    "De Pena, Leonardo": [],
    "De Rosa, Roque": [],
    "De Souza, Nicolás": [],
    "De las Nieves, Lucas": [],
    "De los Santos, Gabriel": [],
    "Dean, Esteban": [],
    "Del Puerto, Ernesto": [],
    "Del, Federico": [],
    "Delfino, Agustín": [],
    "Delfino, Andres": [],
    "Delfino, Danilo": [],
    "Delgado, Juan": [],
    "Delgado, Nicolás": ["Verdirrojo"],
    "Della Mea, Federico": [],
    "Demichelli, José": [],
    "Desirello, Gonzalo": [],
    "Di Domenico, Alejandro": [],
    "Diaz Gavranic, Gonzalo": [],
    "Diaz Grecco, Nicolas": ["Urupan"],
    "Diaz, Agustín": [],
    "Diaz, Fabian": [],
    "Diaz, Gonzalo": [],
    "Diaz, José": [],
    "Diaz, Martin": ["Auriblanco"],
    "Diaz, Maximiliano": [],
    "Diez, Ignacio": [],
    "Digenio, Stefano": [],
    "Dogliotti, Mateo": [],
    "Dominguez, Mauro": [],
    "Domínguez, Fabio": [],
    "Donegana, Juan": [],
    "Dos Santos, Agustín": [],
    "Ducase, Juan": [],
    "Dudoy, Martín": [],
    "Dudoy, Sebastián": [],
    "Dufrechou, Marcel": [],
    "Dumpierrez, Nicolas": [],
    "Elhordoy, Enrique": ["Verdirrojo"],
    "Elicegui, Francisco": [],
    "Elizalde, Raúl": [],
    "Ellis, Mauricio": [],
    "Ellis, Nicolas": [],
    "Ellis, Ramiro": [],
    "Errico, Pablo": [],
    "Escapa, Alejandro": [],
    "Escudero, Juan": [],
    "Espindola, Agustin": [],
    "Espindola, Gianfranco": [],
    "Espinoza, Edison": [],
    "Etcheverry, Nicolás": ["Auriblanco"],
    "FAROPPA, Angel": [],
    "Fajardo, Pablo": [],
    "Fallabrino, Federico": [],
    "Faluotico, Pablo": [],
    "Fedrou, Agustin": [],
    "Fernández Brasil, José": [],
    "Fernández, Darwin": [],
    "Fernández, Fabián": [],
    "Fernández, Federico": [],
    "Fernández, Gerardo": [],
    "Fernández, Guido": [],
    "Fernández, Ignacio": ["Verdirrojo"],
    "Fernández, José": [],
    "Fernández, Juan": ["Verdirrojo"],
    "Fernández, Matías": [],
    "Fernández, Rodrigo": [],
    "Ferrari, Bruno": [],
    "Ferrari, Sebastián": [],
    "Ferreira, Ariel": [],
    "Ferreira, Fernando": [],
    "Ferreira, Gonzalo": [],
    "Ferreira, Guido": ["Auriblanco"],
    "Ferreira, Marcelo": [],
    "Ferrin, Juan Pablo": [],
    "Ferro, Fernando": [],
    "Ferrés, Andrés": [],
    "Figueiredo, Carlos": [],
    "Finozzi, Gabriel": [],
    "Fiorelli, Walter": [],
    "Firpo, Nicolás": [],
    "Fittipaldo, Bruno": [],
    "Flores, Matias": ["Verdirrojo"],
    "Folena, Facundo": [],
    "Fontan, Jio": [],
    "Fontes, Agustín": [],
    "Forcade, Ignacio": ["Auriblanco", "Verdirrojo"],
    "Franchetti, Esteban": [],
    "Franzozi, Ignacio": [],
    "Freira, Santiago": [],
    "Frigio, Mariano": [],
    "Frontán, Joaquín": [],
    "Frugoni, Diego": [],
    "Frutos, Andrés": ["Auriblanco"],
    "Frutos, Marcelo": [],
    "Fuentes, Gonzalo": [],
    "Fuentes, Santiago": [],
    "GONZALEZ, Nicolas": [],
    "Gabín, Andrés": ["Urupán"],
    "Gadnich, Ignacio": [],
    "Gago, Jose": [],
    "Galego, Nahuel": [],
    "Galleto, Juan Andres": [],
    "Gallo Besio, Pablo": [],
    "Gallo, Ariel": [],
    "Gallo, Matías": [],
    "Gallo, Mauricio": [],
    "Galván, Gervasio": [],
    "Galván, Víctor": ["Urupán"],
    "Gamon, Leandro": [],
    "Garay, Martín": [],
    "Garbarino, Juan": [],
    "Garcia, Nicolas": [],
    "García, Claudio": [],
    "García, Diego": ["Verdirrojo"],
    "García, Esteban": [],
    "García, Francisco": [],
    "García, Gonzalo": [],
    "García, Pablo": [],
    "Gares, Daniel": [],
    "Gargallo, Ezequiel": ["Urupan"],
    "Garland, Pablo": [],
    "Garriga, Alvaro": [],
    "Gasanol, Matías": [],
    "Gastañaga, Felipe": ["Auriblanco"],
    "Gauna, Carlos": [],
    "Geller, Marcos": [],
    "Gelos, José": [],
    "Gentile, Agustin": [],
    "Gentini, Nicolás": ["Auriblanco", "Verdirrojo"],
    "Geraldo, Agustín": [],
    "Gervasini, Carlos": ["Verdirrojo"],
    "Gestal, Santiago": [],
    "Ghans, Alvaro": ["Urupán"],
    "Giacometti, Mattía": [],
    "Giacometti, Renzo": [],
    "Giano, Emiliano": [],
    "Gilardi, Marcio": [],
    "Gilardoni, Gaston": [],
    "Giles, Fernando": [],
    "Gimenez, Geronimo": [],
    "Girbau, Tadeo": [],
    "Gobba, Sebastián": [],
    "Godoy, Rodolfo": [],
    "Gomez, Gabriel": [],
    "Gonzalez Cabrera, Marcelo": [],
    "Gonzalvo, Gonzalo": [],
    "González Aguirre, Sebastián": [],
    "González Espino, Sebastian": [],
    "González Fernández, Rodrigo": [],
    "González Muñoz, Marcelo": [],
    "González, Andrés": [],
    "González, Diago": [],
    "González, Diego": [],
    "González, Emiliano": [],
    "González, Ignacio": [],
    "González, Juan Gabriel": [],
    "González, Rodrigo": [],
    "Gordienko, Juan": [],
    "Gordillo, Nicolás": [],
    "Goyen, Gabriel": [],
    "Goyeneche, Fernando": [],
    "Goyeneche, Mauricio": [],
    "Granger, Jason": [],
    "Graña, Diego": [],
    "Greising, Nicolás": [],
    "Grolero, Rodolfo": [],
    "Grolla, Facundo": [],
    "Gruzdas, Andrés": [],
    "Guerra, Emiliano": [],
    "Guerra, Juan": [],
    "Guerra, Lucas": [],
    "Guerra, Matías": ["Verdirrojo"],
    "Guillen, Andrés": [],
    "Gutierrez, Fernando": [],
    "Gutierréz, Fernando": [],
    "Gómez, Jair": [],
    "Gómez, Juan Ignacio": [],
    "Gómez, Rodrigo": [],
    "Haller, Emanuele": [],
    "Hammer, Friddi": [],
    "Hellman, Facundo": [],
    "Herasimechuck, Alexis": [],
    "Hernández, Diego": [],
    "Hernández, Esteban": ["Verdirrojo"],
    "Hernández, Facundo": [],
    "Hernández, Matías": [],
    "Holms, Philip": [],
    "Hornos, Augusto": [],
    "Hornos, Paul": [],
    "Horvat, Stefan": [],
    "Hourcade, Marcos": [],
    "Ibarra, Martín": [],
    "Ibarra, Nicolás": [],
    "Ibón,Pablo": [],
    "Iglesia, Fernando": [],
    "Iglesias, Agustín": [],
    "Iglesias, Gonzalo": [],
    "Ijes, Nicolás": [],
    "Illaramendi, Jan": [],
    "Insausti, Ernesto": [],
    "Insua, Sntiago": [],
    "Inthamoussu, Víctor": [],
    "Introini, Luis": [],
    "Invernizzi, Camilo": [],
    "Iribarren, Alejandro": [],
    "Irureta, Javier": [],
    "Izaguirre, Sebastián": [],
    "Izaguirre,. Rodrigo": [],
    "Izaurralde, Facundo": [],
    "Izuibejeres, Joaquín": [],
    "Izuibejeres, Matías": [],
    "Jennings, Timothy": ["Verdirrojo"],
    "Jones, Andrés": ["Auriblanco"],
    "Jones, Joaquín": ["Auriblanco"],
    "Jones, Michael": ["Verdirrojo"],
    "Jorcín, Leonardo": [],
    "Juan, Nicolás": [],
    "Jubin, Alejandro": [],
    "Juárez, Federico": [],
    "Kalemkerian, Matias": [],
    "Kanis, Brad": [],
    "Kanovich, Sebastián": [],
    "Klisich, Santiago": [],
    "Koster, Nicolás": [],
    "Laborda, Adrian": [],
    "Lacues, Ismael": [],
    "Lado, Matias": [],
    "Laduche, Gastón": [],
    "Lagomarsino, Bruno": [],
    "Lamas, Juan": [],
    "Lambert, Abel": ["Urupán"],
    "Lambert, Eduardo": ["Verdirrojo"],
    "Lapaz, Hugo": [],
    "Laplazotte, Jorge": [],
    "Larre, Francisco": [],
    "Larrea, Gonzalo": [],
    "Lasarga, Martín": ["Urupán"],
    "Laubert, Pablo": [],
    "Lazzaroni, Renzo": [],
    "Ledanis, Alejandro": [],
    "Leguizamón, Sebastián": [],
    "Leiva, Franco": [],
    "Lema, Gabriel": [],
    "Lema, Juan": [],
    "Lema, Matías": [],
    "Lespada, Diego": [],
    "Lewin, Salomón": [],
    "Lewis, Nicolás": [],
    "León, Santiago": [],
    "Lima, Atilio": [],
    "Lipatin, Daniel": [],
    "Liperman, Fabián": [],
    "Lokais, Emanuel": [],
    "Lopez Garcia, Rodrigo": [],
    "Lopez, Claudio": [],
    "Lopez, Leonardo": [],
    "Lopez, Martin": ["Verdirrojo"],
    "Lopez, Mauro": ["Auriblanco"],
    "Lopez, Nuñez, Mauricio": [],
    "Lopez, Valentin": [],
    "Lorenzo, Matías": ["Auriblanco", "Verdirrojo"],
    "Loriente, Iván": [],
    "Lotitto, Leonardo": ["Urupan"],
    "Lozano, Fernando": [],
    "Luhers, Martin": [],
    "Luzuriaga, Valentín": [],
    "López Cardozo, Andrés": [],
    "López Vilas, Enrique": [],
    "López, Alex": [],
    "López, Damián": [],
    "López, Diego": [],
    "López, Eduardo": [],
    "López, Germán": [],
    "López, Joan Andoni": [],
    "López, Juan": [],
    "López, Rodrigo": [],
    "López, Sebastián": [],
    "MACHADO, Agustín": [],
    "MORALES, Carlos": [],
    "Macanskas, Pablo": [],
    "Macchi, Luca": [],
    "Machado, Christian": [],
    "Machado, Leonardo": [],
    "Machado, Santiago": ["Urunday Universitario"],
    "Mackiewicz, José": [],
    "Maggiari, Andrés": [],
    "Maglione, Juan Bautista": [],
    "Magnone, Luca": [],
    "Magurno, Diego": [],
    "Mainentti, Mauro": [],
    "Maiochi, Agustín": [],
    "Mancebo, Sergio": [],
    "Manicera, Marcelo": [],
    "Manzini Magli, Marco": [],
    "Marchelli, Carlos": [],
    "Marchelli, Ricardo": [],
    "Marenales, Martin": [],
    "Mariani, Bruno": [],
    "Marichal, Alfredo": [],
    "Marichal, Matías": [],
    "Mariño, Rodrigo": [],
    "Marotta, Marcos": [],
    "Marquisa, Facundo": [],
    "Marr, Christian": [],
    "Martines, Guzman": [],
    "Martinez, Agustin": [],
    "Martinez, Hernan": [],
    "Martinez, Ignacio": [],
    "Martinez, Ivan": [],
    "Martinez, Maximiliano": [],
    "Martinez, Raul": [],
    "Martinez, Rodrigo": [],
    "Martinez, Sebastian": ["Verdirrojo"],
    "Martínez Nacere, Diego": [],
    "Martínez Viñoly, Matías": [],
    "Martínez, Andrés": [],
    "Martínez, Diego": [],
    "Martínez, Diego Andrés": [],
    "Martínez, Federico": [],
    "Martínez, Gustavo": [],
    "Martínez, Horacio": [],
    "Martínez, Mauricio": [],
    "Martínez, Oscar": [],
    "Martínez, Osvaldo": [],
    "Martínez, Roney": [],
    "Martínez,Tabaré": [],
    "Masaferro, Gastón": [],
    "Masaferro, Lucas": [],
    "Masner, Federico": [],
    "Massa, Santiago": [],
    "Mateu, Pedro": [],
    "Matienzo, Richard": [],
    "Matoso, Mauricio": [],
    "Maturana, Sebastián": [],
    "Maurno, Nicolas": [],
    "May, Nicolás": [],
    "Mayora, Juan Manuel": [],
    "Mayora, Martin": [],
    "Mazzarino, Nicolás": [],
    "Mazzuchi, Cristian": [],
    "Mazzuco, Federico": [],
    "Medina, Octavio": [],
    "Meira, Gonzalo": [],
    "Melgarejo, Rodrigo": [],
    "Mendaña, Santiago": [],
    "Mendez, Maximiliano": [],
    "Mendia, Ignacio": [],
    "Mendilaharzu, Maximiliano": [],
    "Menéndez, Liber": [],
    "Merelo, Elías": [],
    "Messa, Wilmar": [],
    "Midaglia, Alvaro": [],
    "Miglionico, Julio": ["Yale", "Sayago", "Larre Borges", "Cader"],
    "Miller, Federico": [],
    "Minervini, Diego": ["Verdirrojo"],
    "Miraglia, Álvaro": [],
    "Miramontes, Esteban": [],
    "Miranda, Mauro": [],
    "Modernell, Juan": ["Verdirrojo"],
    "Modernell, Maximiliano": [],
    "Moglia, Santiago": [],
    "Monetti, Maurizio": [],
    "Monroe, Tarrie": ["Yale", "Sayago", "Romis Nelimar", "Larre Borges", "Cader"],
    "Montemurro, Germán": [],
    "Montemurro, Gustavo": ["Cader"],
    "Monterroso, Ignacio": ["Cader"],
    "Monterroso, Santiago": [],
    "Monterroso,. Julio": [],
    "Monteverde, Felipe": [],
    "Monteverde, Manuel": ["Verdirrojo", "Larre Borges"],
    "Morales, Alexis": [],
    "Morales, Pablo": [],
    "Morales, Sebastian": ["Verdirrojo"],
    "Morena, Andrés": [],
    "Morencos, Ignacio": [],
    "Moreno, Maximiliano": [],
    "Muela, Claudio": [],
    "Muguiro, Diego": ["Auriblanco"],
    "Muniz, Jorge": [],
    "Muniz, José": [],
    "Munoz, Martín": ["Urupán"],
    "Munoz, Sebastián": ["Verdirrojo"],
    "Mussio, Maximiliano": [],
    "Mónico, Mauro": [],
    "Nalerio, Agustin": [],
    "Narbais, Fabián": ["Verdirrojo"],
    "Nathan, Guillermo": ["Urupán"],
    "Navarrete, Freddy": [],
    "Navarrine, Mauro": [],
    "Nessi, Marcelo": [],
    "Nicoletti, Matías": [],
    "Nieto, Julio": [],
    "Nieves, Josuel": [],
    "Niquichenco, Gerardo": ["Verdirrojo", "Sayago", "Goes", "Cader", "Romis Nelimar"],
    "Niquichenco, Gustavo": [],
    "Nobile, Maximiliano": [],
    "Noe, Santiago": ["Verdirrojo", "Yale"],
    "Nogueira, Alexis": [],
    "Nuevo, Raúl": [],
    "Nunez, Nicolas": [],
    "Oholeguy, Matías": [],
    "Ojeda, Nicolás": ["Verdirrojo"],
    "Olejnik, Luis": [],
    "Olivera, Diego": [],
    "Olivera, Franco": [],
    "Olivera, Nicolás": [],
    "Olivera, Rodrigo": [],
    "Olivera, Ruben": [],
    "Onetto, Ismael": [],
    "Opperti, Sebastián": [],
    "Ordoño, Fernando": [],
    "Ormando, Renzo": [],
    "Ormechea, Joaquín": ["Cader"],
    "Ortega del Rio, Joaquín": [],
    "Ortega del Rio, Juan Manuel": [],
    "Ortiz, Ignacio": ["Cader"],
    "Osimani, Joaquín": [],
    "Osimani, Martín": [],
    "Osores, Schubert": [],
    "Otatti, Edgardo": [],
    "Otonello, Marcos": [],
    "Ottonello, Sebastián": [],
    "Oviedo, David": [],
    "Owens, Trelonnie": ["Welcome", "Sayago", "Biguá", "Larre Borges", "Romis Nelimar"],
    "Oxandabarat, Germán": ["Verdirrojo"],
    "PASSOS, Hatila de Souza": [],
    "Pacheco, Gustavo": [],
    "Pacilio, Alvaro": [],
    "Paez, Gonzalo": [],
    "Pagani, Gianni": ["Cader"],
    "Palacios, Fabrizio": [],
    "Palarino, Lucas": ["Cader"],
    "Palavecino, Washington": [],
    "Pancic, Juan": [],
    "Panelli, Julio": ["Auriblanco"],
    "Panowski, Joaquín": [],
    "Paolillo, Federico": ["Yale"],
    "Papariello, Tabaré": [],
    "Paradiso, Mathias": [],
    "Pardo, Adrian": [],
    "Paredes, Alfredo": [],
    "Parodi, Luciano": [],
    "Parodi, Ruben": ["Auriblanco"],
    "Parra, Mauricio": [],
    "Parreno, Mauricio": ["Verdirrojo"],
    "Pasini, Gonzalo": [],
    "Pasqualli, Federico": [],
    "Pastorino, Sebastián": [],
    "Pastrana, Ciro": [],
    "Pau, Julián": [],
    "Pavón, Agustin0": [],
    "Penna, Martín": [],
    "Pepe, Nicolás": ["Yale"],
    "Peralta, Matías": [],
    "Peralta, Pablo": [],
    "Perdomo, Martin": [],
    "Pereira das Neves, Gustavo": [],
    "Pereira, Cristian": [],
    "Pereira, Darío": ["Sayago"],
    "Pereira, Federico": [],
    "Pereira, Martín": [],
    "Pereira, Nicolas": [],
    "Pereira, Pablo": ["Urupan"],
    "Perera, Guzmán": [],
    "Pereyra, Diego": [],
    "Pereyra, Javier": ["Cader"],
    "Pereyra, Luis": [],
    "Perez, Julian": ["Verdirrojo"],
    "Perez, Lautaro": [],
    "Perez, Nicolas": [],
    "Perona, Mateo": [],
    "Pessano, Daniel": [],
    "Picasso, Federico": [],
    "Piedrabuena, Ariel": [],
    "Pierri, Luis": [],
    "Pineiro, Andrés": ["Verdirrojo", "Yale", "Auriblanco", "Cader"],
    "Pineiro, Ezequiel": [],
    "Pineiro, Joaquín": [],
    "Pintos, Leandro": ["Sayago", "Yale", "Praga", "Lagomar", "De Agosto"],
    "Pintos, Rodrigo": [],
    "Piovano, Enzo": [],
    "Pita, Hernán": [],
    "Pizzani, Diego": [],
    "Pizzini, Nicolás": [],
    "Planells, Luciano": [],
    "Polvarini, Luciano": ["Romis Nelimar"],
    "Polvarini, Mauro": ["Romis Nelimar"],
    "Pomoli, Fausto": [],
    "Pons, Ignacio": ["Yale", "Larre Borges", "Goes", "De Agosto", "Atenas"],
    "Pons, Juan": ["Sayago"],
    "Pons, Maximiliano": [],
    "Ponte, Mauricio": [],
    "Porfilio, Agustín": [],
    "Posada, Enrique": [],
    "Pose, Mateo": [],
    "Posse, Agustín": [],
    "Pozzolo, Ignacio": [],
    "Prato, Diego": ["Verdirrojo", "Cader"],
    "Prego, Francisco": [],
    "Premazzi, Diego": [],
    "Premuda, Fernando": [],
    "Previatti, Rafael": [],
    "Puig, Guillermo": [],
    "Puyol, Ruben": [],
    "Pérez, Alejandro": [],
    "Pérez, Diego": ["Welcome", "Cordón", "Goes", "Urunday Universitario"],
    "Pérez, Fabián": [],
    "Pérez, Ignacio": [],
    "Pérez, Marcelo": ["Welcome", "Sayago", "Yale", "San Lorenzo", "Biguá", "Bohemios", "Larrañaga", "Nacional", "Atenas"],
    "Pérez, Mateo": [],
    "Pérez, Rodrigo": ["Larre Borges", "Tabaré"],
    "Píriz, Gabriel": ["Verdirrojo"],
    "Quijano, Gonzalo": [],
    "Quinteros, Enrique": ["Yale", "Goes"],
    "Quiroga, Martín": [],
    "ROBAINA, Gabriel": ["Auriblanco", "Verdirrojo"],
    "Rafaelli, Daniel": [],
    "Raggioto, Mathías": [],
    "Rak, Pablo": ["San Lorenzo", "Trouville", "Defensor Sporting", "Bohemios", "Biguá", "Cader"],
    "Rama, Federico": ["Yale", "Bohemios"],
    "Ramirez, Santiago": ["Larre Borges", "Tabaré"],
    "Ramírez, Alvaro": ["Sayago", "Bohemios", "Waston", "Defensor Sporting"],
    "Rava, Renzo": ["Hebraica", "Larre Borges", "Hebraica Macabi", "Urunday Universitario", "Romis Nelimar"],
    "Realan, Marcelo": [],
    "Refresquines, Luis": [],
    "Regalado, Juan Martin": ["Tabaré"],
    "Reig, Gustavo": [],
    "Reina, Fabián": ["Tabaré", "Hebraica"],
    "Ressi, Matias": ["Sayago", "Larre Borges", "Cader"],
    "Retamoso, Joaquín": ["Tabaré"],
    "Rey, Agustín": [],
    "Rey, Santiago": [],
    "Reyes, Manuel": [],
    "Reyes, Pablo": [],
    "Reymondez, Adrián": ["Yale", "Trouville", "Tabaré", "Unión Atlética"],
    "Riba, Sebastián": [],
    "Riera, Rodrigo": ["Welcome", "Cordón", "Trouville", "Defensor Sp.", "Larre Borges", "Cader"],
    "Riezler, Nicolás": ["Tabaré"],
    "Risso, Matias": [],
    "Rivas, Gonzalo": ["Tabaré", "Urunday Universitario", "Welcome"],
    "Rivas, Matías": ["Larre Borges"],
    "Riveiro, Camilo": ["Sayago"],
    "Rivera, Juliano": ["Welcome", "Aguada", "Tabaré", "Hebraica", "Trouville"],
    "Rivero, Daniel": ["Welcome", "Sayago", "Yale", "Goes", "Trouville", "Defensor Sporting", "Bohemios", "Olimpia", "Aguada", "Cader", "De Agosto"],
    "Rivero, Rodrigo": ["Auriblanco", "Verdirrojo"],
    "Rivero, Sergio": ["Yale"],
    "Robaina, Mathias": [],
    "Rocha, Pablo0": ["Goes"],
    "Rocha, Santiago": [],
    "Rodeghiero, Gabriel": [],
    "Rodriguez Delfino, Santiago": ["Larre Borges"],
    "Rodriguez Freitas, Santiago": [],
    "Rodriguez Olivera, Juan Manuel": ["Tabaré"],
    "Rodriguez, Andres": [],
    "Rodriguez, Enzo": [],
    "Rodriguez, Juan": [],
    "Rodriguez, Juan Pedro": [],
    "Rodriguez, Lucas": ["Verdirrojo", "Aguada"],
    "Rodriguez, Mateo": [],
    "Rodríguez Delfino, Santiago": [],
    "Rodríguez Santana, Horacio": [],
    "Rodríguez, Alex": ["Tabaré", "Goes", "Defensor Sporting", "Cordón", "Juventud"],
    "Rodríguez, Dionisio": [],
    "Rodríguez, Emilio": [],
    "Rodríguez, Johnny": ["Welcome", "Sayago", "Yale", "Goes", "Cordón", "Trouville", "Defensor Sporting", "Bohemios", "Tabaré", "Unión Atlética", "Larre Borges", "Romis Nelimar"],
    "Rodríguez, Pablo": ["Cader"],
    "Rodríguez, Pedro": ["Tabaré", "Romis Nelimar"],
    "Rodríguez, Ramiro": [],
    "Rodríguez, Santiago": ["Tabaré"],
    "Rodríguez, Yannick": ["Tabaré"],
    "Rojas, Martín": [],
    "Romero, Diego": ["Welcome", "Goes"],
    "Romero, Gaston": ["Cader"],
    "Romero, Gustavo": ["Cordón", "Larre Borges", "Olivol Mundial"],
    "Rompani, Bruno": ["Romis Nelimar"],
    "Román, Gonzalo": [],
    "Ronco, Federico": ["Tabaré", "Romis Nelimar"],
    "Rondeau, Luís": [],
    "Roselli, Facundo": ["Hebraica", "Cader", "Anastasia", "Yale"],
    "Roses, Marcelo": ["Sayago"],
    "Rosmarino, Nicolás": ["Larre Borges", "De Agosto"],
    "Rostán, Jesús": ["Cordón", "Goes", "Sayago", "Waston"],
    "Rovira, Juan": [],
    "Rusch, Pierino": ["Hebraica", "Hebraica Macabi"],
    "SAAVEDRA, Agustín": [],
    "Salas, Santiago": [],
    "Saldanha, Víctor": ["Auriblanco", "Verdirrojo", "Urunday", "Atenas", "Olivol Mundial", "De Agosto", "Montevideo", "Urunday Universitario", "Cader", "Romis Nelimar"],
    "Salvia, Roberto": ["Yale", "Stockolmo"],
    "San Miguel, Andrés": ["Sayago", "Yale", "Anastasia", "Defensor Sporting", "Biguá", "Nacional"],
    "Sanchez, Federico": ["Yale", "Nacional", "Cordón"],
    "Santos, Nahuel": [],
    "Santos, Nahuel0": [],
    "Saravia, Mathías": ["Goes", "Olivol Mundial"],
    "Saucedo, Jorge": ["Praga", "Verdirrojo", "Tabaré", "Atenas"],
    "Saudaskas, Alvaro": ["Stockolmo", "Cordón"],
    "Scarpenti, Ignacio": [],
    "Schneck, Kevin": [],
    "Seguessa, Federico": ["Auriblanco"],
    "Sellanes, Carlos": ["Hebraica", "Olivol Mundial"],
    "Serqui, Carlos": [],
    "Serres, Emiliano": ["Tabaré"],
    "Sgorlo, Aníbal": ["Yale", "Lagomar"],
    "Shamlián, Daniel": ["Verdirrojo", "Juventud"],
    "Shaw, Sebastián": [],
    "Shellman, Terence": ["Sayago", "Tabaré"],
    "Sienra, Mauricio": [],
    "Sierra, Fernando": ["Waston", "Stockolmo"],
    "Sierra, Hugo": ["Welcome", "Plaza", "Bohemios", "Trouville", "Malvín", "Hebraica", "Nacional"]
  }
}
